##
## EPITECH PROJECT, 2021
## B-CPE-110-MPL-1-1-BSQ-nicolas.spijkerman
## File description:
## Makefile
##

all:
	@make -C my/

clean:
	@make clean -C my/

fclean:
	@make fclean -C my/
	@rm -rf *.a

re : fclean all
